cornell-zhang/allo

.github/workflows/sphinx_build.yml, README.md, docs/source/conf.py, docs/source/index.rst
This PR updates the README and documentation file for open-source purposes.
=> [README] Update README file and documentations

allo/backend/hls.py, allo/backend/ip.py, playground/int8_gemm.py, tests/ip_integration/test_external.py, tests/pytorch/test_linear.py, tests/test_builder.py, tests/test_systolic_array.py, tests/test_vhls.py
This PR adds a utility function `hls.is_available()` for testing if the Vitis/Vivado environment is correctly installed.
=> [backend] Add utility function `hls.is_available()`

allo/backend/ip.py, tests/test_vhls.py
This PR adds a hash value to the generated pybind library to avoid possible conflicts when calling csim for multiple schedules.
=> [IP] Add hash value to pybind library

README.md
This PR updates the README file for related projects (sorted in alphabetical order).
=> [README] Update README for related projects

allo/ir/transform.py
This PR adds a `rewind` option to the `pipeline` pragma when generating the IO loops for the application. This PR fixes #143.
=> [Backend] Rewind IO loops

allo/library/__init__.py, allo/library/nn.py, examples/README.md, examples/transformer_hls.py, tests/test_nn.py
This PR provides predefined schedules for each kernel in `nn.py` so that the generated HLS kernels are already optimized with pragmas inserted.
=> [lib] Add schedules to nn lib

allo/backend/ip.py, allo/ir/builder.py, allo/passes.py, tests/ip_integration/test_external.py, tests/ip_integration/vadd_int.cpp, tests/ip_integration/vadd_int.h
This PR adds scalar support to import external HLS modules.
=> [IP] Add scalar support to external HLS module

.github/workflows/sphinx_build.yml, docs/source/setup/index.rst
This PR tries to fix the documentation deployment failure by creating two separate docker images.
=> [CI] Update sphinx_build script

README.md, build.sh, docs/source/conf.py, docs/source/developer/index.rst, docs/source/setup/index.rst
This PR updates the installation guide in the documentation and the README file.
=> [docs] Update installation guide

.github/workflows/sphinx_build.yml, README.md, docs/source/developer/index.rst, requirements.txt
This PR updates the black formatter version and the corresponding developer documentation. Also, the README file is updated to use the official ACM DOI for our paper.
=> [CI] Fix black version and update docs

allo/backend/hls.py, allo/backend/vitis.py, docs/source/api/index.rst, tutorials/tutorial_02_vhls.py
This PR makes sure the results of on-board execution return correctly back to Python. [This tutorial](https://github.com/cornell-zhang/allo/blob/main/tutorials/tutorial_02_vhls.py) has been verified on the U280 FPGA in a push-button way.
=> [Backend] Fix Vitis on-board execution testing

allo/ir/builder.py, tests/dataflow/test_1D_systolic.py, tests/dataflow/test_smith_waterman_systolic.py
This PR changes the dataflow builder in #253 to explicitly unfold a stream array. This is a requirement for the TAPA backend, which does not support an array of streams.
The generated HLS code for systolic is shown below:
```cpp
void top(
float *v108,
float *v109,
float *v110
) {	// L126
#pragma HLS interface m_axi port=v108 offset=slave bundle=gmem0
#pragma HLS interface m_axi port=v109 offset=slave bundle=gmem1
#pragma HLS interface m_axi port=v110 offset=slave bundle=gmem2
#pragma HLS dataflow
float buf0[2][2];	//
l_S_buf0_buf0_l_0: for (int buf0_l_0 = 0; buf0_l_0 < 2; buf0_l_0++) {	//
l_buf0_l_1: for (int buf0_l_1 = 0; buf0_l_1 < 2; buf0_l_1++) {	//
#pragma HLS pipeline II=1 rewind
float v114 = v108[((buf0_l_0 * 2) + buf0_l_1)];	//
buf0[buf0_l_0][buf0_l_1] = v114;	//
}
}
float …
```
=> [dataflow][builder] Explicitly unfold stream array

tests/dataflow/test_daisy_chain_gemm.py
This PR enhanced previous daisy-chain SA by adding multi C/output caches.
See the example code inside.
=> [dataflow] Add multi C/output caches for daisy-chain SA example

docs/source/conf.py, docs/source/dive/ip.rst, docs/source/dive/pytorch.rst, docs/source/index.rst, tutorials/dive_01_data_types.py, tutorials/dive_02_template.py, tutorials/dive_03_composition.py, tutorials/dive_04_features.py, tutorials/tutorial_01_get_started.py
This PR adds new documents to introduce the features in Allo, including:
1. [Data Types and Type Casting](https://cornell-zhang.github.io/allo/gallery/dive_01_data_types.html)
2. [Template Kernels](https://cornell-zhang.github.io/allo/gallery/dive_02_template.html)
3. [Kernel Composition](https://cornell-zhang.github.io/allo/gallery/dive_03_composition.html)
4. [IP Integration](https://cornell-zhang.github.io/allo/dive/ip.html)
5. [PyTorch Integration](https://cornell-zhang.github.io/allo/dive/pytorch.html)
6. [Other Features](https://cornell-zhang.github.io/allo/gallery/dive_04_features.html)
=> [docs] Add documents on Allo features

.github/workflows/config.yml, .github/workflows/sphinx_build.yml, allo/backend/aie.py, docs/source/backends/aie.rst, docs/source/index.rst, docs/source/setup/index.rst
This PR adds documentation for the installation guide of the AIE backend.
=> [doc] Add AIE backend installation guide

allo/backend/hls.py, allo/backend/llvm.py, allo/harness/vitis/README.md, tutorials/tutorial_02_vhls.py
This PR
1. Fixes the incorrect mode when calling vhls
2. Add number of arguments checking when calling HLS modules
3. Update HLS tutorial to make it clear (removing the unnecessary csyn discussion)
=> [docs] Update HLS tutorial

allo/backend/ip.py, allo/library/systolic.py, allo/passes.py, docs/source/dive/ip.rst, tests/ip_integration/test_external.py, tests/ip_integration/vadd_4d.cpp, tests/ip_integration/vadd_4d.h
This PR correctly handles the external function when analyzing the IO information, allowing IPModule to be synthesized with HLS tools.
=> [IP] Fix PyBind and HLS backend for IPModule

allo/dataflow.py, allo/ir/builder.py, allo/utils.py, mlir/lib/Translation/Utils.cpp, tests/dataflow/test_df_unit.py
This PR adds unsigned type annotation to the stream construct. This PR fixes #298.
=> [dataflow] Support UInt stream

.github/workflows/config.yml, .gitignore, README.md, allo/verify.py, docs/source/backends/aie.rst, docs/source/backends/llvm.rst, docs/source/backends/simulator.rst, docs/source/backends/tapa.rst, docs/source/backends/vitis.rst, docs/source/dive/ip.rst, docs/source/dive/pytorch.rst, docs/source/index.rst, requirements.txt, tutorials/dive_05_verifier.py, tutorials/tutorial_01_get_started.py
This PR makes several changes to the README and documents:
1. Add citations to our FPGA'25, FPGA'24, and FCCM'24 papers in the README.
2. Change the badge from CircleCI to Github Action.
3. Install the verifier by default.
4. Fix the logic of finding live-out variables in the verifier.
5. Add documents for multiple backends (LLVM, Vitis, TAPA, simulator, AIE, and verifier)
=> [docs] Add backend docs and fix verifier

allo/__init__.py, allo/backend/hls.py, allo/customize.py, playground/int8_gemm.py, tests/dataflow/test_systolic.py, tests/dataflow/test_unified_systolic.py, tests/test_systolic_array.py, tests/test_vhls.py
This PR fixes #333.
1. Allow users to directly specify the buffer (using string) for partition
2. Fix some csyn/hw_emu incorrect number of arguments issue
=> [Fix] Fix legacy systolic array tests

allo/backend/aie.py, allo/ir/builder.py, tests/dataflow/aie/test_tp.py
This PR adds a `map_kernels_to_device_mesh` function to map multiple kernels to an AIE device. Each kernel is guaranteed not to overlap. Also, a tensor parallel example is provided.
```python
def _test_tensor_parallelism():
Ty = int32
M, K, N, L = 8, 8, 8, 8
P0 = 2
Nt = N // P0
@df.region()
def top():
Y = df.array(df.pipe(dtype=Ty, shape=(M, Nt), depth=2), shape=(P0,))
part_Z = df.array(df.pipe(dtype=Ty, shape=(M, L), depth=2), shape=(P0,))
@df.kernel(mapping=[P0])
def gemm0(X: Ty[M, K], W1: Ty[K, N] @ LyW1):
pn = df.get_pid()
Y[pn].put(allo.matmul(X, W1))
@df.kernel(mapping=[P0])
def gemm1(W2: Ty[N, L] @ LyW2):
pn = df.get_pid()
part_Z[pn].put(allo.matmul(Y[pn].get(), W2))
def acc(Z: Ty[M, L]):
Z[:, :] = allo.add(part_Z[0].get(), part_Z[1].get())
X = …
```
=> [Dataflow][AIE] Add device mapping heuristics and tensor parallel example

allo/autoscheduler/dfg.py, allo/autoscheduler/passes.py, examples/polybench/two_mm.py, tests/autoscheduler/test_passes.py
Fixes some bugs introduced in the autoscheduler passes that were discovered during testing. 
Bug 1: void type methods were not correctly handled when solving optimization problem (no sink node). 
Bug 2: stream read operations in reduction loops were not correctly guarded and causing sw/hw_emu to hang. 
Bug 3: reduction loops were not correctly handled in dataflow canonicalization pass (only the innermost induction variable was treated as the only reduction variable)
Bug 1: for void methods, there are multiple sinks created and the optimization formulation now seeks to minimize the max of the last write times for each. 
Bug 2,3: Correct guard if statements introduced to ensure reduction loop behavior is correct. 
All tests are now passing sw_emu & hw_emu.
Reads from stream in reduction …
=> [Autoscheduler][Fix] Bug fixes and improvements

allo/autoscheduler/config.py, allo/autoscheduler/dfg.py, allo/autoscheduler/passes.py, allo/autoscheduler/primitives.py, tests/autoscheduler/test_autoscheduler.py, tests/autoscheduler/test_canonicalization.py, tests/autoscheduler/test_dfg.py, tests/autoscheduler/test_passes.py
This PR implements the schedule extraction from the node parallel MINLP PR (https://github.com/cornell-zhang/allo/pull/362) and also contains some bug fixes and improvements for the MINLP construction. Notably, all performance models can now be constructed from a generalized version of the MINLP.
Based on the MINLP solution, the appropriate loop split factors are computed and buffers are explicitly partitioned into an n-d array of FIFOs. For instance, if we have a buffer of 10x10 and some pseudocode that looks like this 
```python
for j in range(10):
read arr[i][j]
```
with loop tiling factors Ti = 2, Tj = 2, the transformation yields
```python
for j in range(10):
read arr[i%2][j%2][i//2][j//2]
```
The modulo and floor division are elided after the …
=> [Autoscheduler] Node Parallel Schedule

allo/autoscheduler/dfg.py, allo/autoscheduler/passes.py, tests/autoscheduler/test_autoscheduler.py, tests/autoscheduler/test_passes.py
This PR adds the combined optimization (solving for loop permutation and tiling factors simultaneously) described in the stream-hls paper. This uses the generalized performance model introduced in the node-level parallelization PR. 
Further, all the original graph-level parallelization method has been deprecated and replaced by the generalized model. 
=> [Autoscheduler] Combined Graph/Node Optimization

allo/backend/llvm.py, allo/customize.py, allo/ir/transform.py, tests/test_schedule_memory.py
Fix issue #378, make sure when you partition the return tensor of a call op, the callee function and the users are also updated to have the correct data type.
Recursive partition doesn't handle updating function type update and user function update.
https://github.com/cornell-zhang/allo/blob/dd2ab1c5b0d070bf2cca1deda1bfb96109db7a66/allo/customize.py#L320-L361
- Update `recursive_partition` to follow the callee function and subsequent usage of a target tensor
- Update callee function type, return type, return tensor allocation, subsequent usage
- Recursively update function call types to propagate the partition info.
Here's an example where the return tensor of a function call is partitioned, and the partition info should be propagated to the callee function and all subsequent function …
=> [Primitive] Fix Partition Propagation (Fix #378)

allo/backend/aie/__init__.py, tests/dataflow/aie/gpt2/test_gpt2_block.py, tests/dataflow/aie/test_matrix.py, tests/dataflow/aie/test_vector.py
This PR provides an `is_available` function for users to check whether the AIE backend is correctly set up.
```python
import allo.backend.aie as aie
print(aie.is_available())
```
=> [Backend][AIE] Add is_available to the AIE backend

allo/autoscheduler/dfg.py, allo/autoscheduler/passes.py, allo/autoscheduler/primitives.py, allo/autoscheduler/util.py, allo/backend/aie/__init__.py, allo/backend/aie/mapping.py, allo/backend/aie/mlir_codegen.py, allo/backend/aie/utils.py, allo/backend/aie/vliw.py, allo/ir/builder.py, allo/ir/infer.py, tests/dataflow/aie/test_vliw.py
It is a tedious process to write C kernels for the AIE VLIW processors, which involves complicated code rewriting and optimization. This PR takes the first step by exposing the Python interface for users to define these "external functions". We reuse the Allo frontend parser, the MLIR builder, and the C codegen to translate a Python program into a C kernel.
Currently, it only supports scalar kernels with straightforward translation. Later on, we need to add vectorization support using the MLIR vector dialect.
The proposed interface is shown below. Users can use `@vliw.kernel()` to decorate their Python kernel, which will be later translated into a C kernel.
```python
def test_simple_add():
@vliw.kernel()
def simple_add(a: float32[16], b: float32[16]) -> float32[16]:
c: float32[16] = 0.0 …
```
=> [Backend][AIE] Generate scalar code for VLIW processor from Python
