allo/backend/hls.py, allo/customize.py, allo/ir/transform.py, allo/primitives/__init__.py, allo/primitives/relay.py, tests/ip_integration/test_external.py, tests/ip_integration/vadd.cpp, tests/ip_integration/vadd_extern.cpp, tests/ip_integration/vadd_extern.h, tests/test_vhls.py
This PR unifies the csim and hw/sw_emu interface. Previously the csim interface will generate explicit arrays for pybind to operator. However, this is not necessary, and pybind can work on pointer interface. Therefore, we do not need two different codegens for csim and hw/sw_emu, which can also make sure the simulated code is exactly the code used to generate hardware accelerator.
Since the dataflow interface may need to change the function arguments, the `generate_input_output_buffers` and `update_interface` passes are both moved into the `HLSModule`. The implementation of the `.to()` primitive is now separated from the `customize.py` file to enable other files to invoke it.
```python
def test_vitis_gemm():
def gemm(A: int32[32, 32], B: int32[32, 32]) -> int32[32, 32]:
C: int32[32, 32] = …
```
=> [Backend] Unify csim and hw/sw_emu codegen

allo/ir/builder.py, allo/ir/infer.py, tests/test_builder.py
This PR adds support for comment blocks inside the Allo kernels, which should fix #145.
=> [Builder] Support comment blocks for Allo kernels

allo/ir/builder.py, tests/test_builder.py
This PR fixes different ways of writing a function without an actual return value and enhances the exception mechanism for function declaration.
```python
def test_build_none_return():
def kernel0(A: int32[32]):
return None
s0 = allo.customize(kernel0)
def kernel1(A: int32[32]) -> None:
return None
s1 = allo.customize(kernel1)
def kernel2(A: int32[32]):
return
s2 = allo.customize(kernel2)
def kernel3(A: int32[32]) -> None:
return
s3 = allo.customize(kernel3)
def kernel4(A: int32[32]):
pass
s4 = allo.customize(kernel4)
def kernel5(A: int32[32]) -> None:
pass
s5 = allo.customize(kernel5)
```
=> [Builder] Fix None Return

allo/customize.py, allo/ir/transform.py, allo/ir/utils.py, tests/test_schedule_compose.py, tests/test_utils.py
This PR unifies the naming convention of `LoopWrapper` and `MockBuffer`. The `LoopWrapper` will explicitly contain the func_name info, which is separated by `:`. The full name is labeled as `<func>:<band>.<loop>`. This PR fixed #155.
=> [Utils] Unify loop utils naming convention

allo/backend/ip.py, allo/customize.py
This PR fixes the potential issue introduced by #156. If users call `.dataflow` to an inner loop, it may not correctly attach the attribute to the loop.
This PR also adds `ap_int<128>` to the `c2allo` type, so that the systolic array examples can be correctly executed.
=> [Primitive] Fix dataflow attribute

allo/library/nn.py
This PR fixes #161 by renaming the intermediate variables. Results from running HLS are attached below.
```
+-------------------+-----------------------------------+
| HLS Version       | Vivado HLS 2019.2.1               |
| Product family    | zynq                              |
| Target device     | xc7z020-clg484-1                  |
| Top Model Name    | softmax                           |
+-------------------+-----------------------------------+
| Target CP         | 10.00 ns                          |
| Estimated CP      | 10.510 ns                         |
| Latency (cycles)  | Min 4129573; Max 4129573          |
| Interval (cycles) | Min 4129574; Max 4129574          |
| Resources         | Type        Used    Total    Util |
|                   | --------  ------  ------- …
```
=> [lib] Fix naming issue in the softmax library function

allo/backend/hls.py, allo/harness/vivado/run.tcl
Corrected the parsing of the version returned from g++ version.
G++ 11.4.0 was judged as a "too old" version.
11 * 10 + 4 >= 48 will be working with this change.
4 * 10 + 8 >= 48 will be working with this change.
(Please provide an example of the input program and the expected behavior, e.g., the generated IR.)
=> Corrected vivado_hls g++ version check

allo/library/nn.py, tests/test_nn.py
The PR solves the issue related to numerical overflow during softmax calculation and the scaled_dot_product_attention that utilizes it. In addition, a similar overflow error occurs in the numpy implementation used in `allo/tests/test_nn.py` that generate golden results for testing. The PR fixes this issue by adding a correct `np_softmax()` function in the testing script.
- **Softmax Overflow**: The softmax calculation could result in overflow when handling large input values, causing NaNs in hte output.
- **Incorrect Numpy Softmax Implementation**: In the original test script, `np_out = np.exp(inp) / np.exp(inp).sum(axis=1, keepdims=True)` will cause similar overflow problems in the exponentiation computation.
The softmax function has been updated to subtract the maximum value in each row …
=> [Bugfix] Resolve softmax and sdp overflow for large values

allo/ir/transform.py, tests/test_schedule_compute.py
Add scf ForOp support in get_loops().
Original get_loops() can't identify the scf ForOp.
Add scf ForOp in condition of loop detection.
SCF loop in mlir like:
`scf.for %arg6 = %26 to %28 step %29 { .... }`
can be identified as a loop by get_loops(). 
- [√] PR's title starts with a category (e.g. [Bugfix], [IR], [Builder], etc)
- [√] Changes are complete (i.e. I finished coding on this PR)
=> [Bugfix] Add scf ForOp support in get_loops()

allo/ir/builder.py, tests/test_builder.py
This PR fixes #173.
As MLIR does not have a `NOT` operation, we need to use `xori` or `cmpi` to achieve the equivalent functionality. This PR use `flag == 0` to simulate `not flag`.
```python
def test_not():
def kernel[Ty](flag: bool) -> "Ty":
X: Ty
if not flag:
X = 1
else:
X = 0
return X
s = allo.customize(kernel, instantiate=[int8])
assert mod(True) == 0
assert mod(False) == 1
```
```mlir
module {
func.func @kernel(%arg0: i1) -> i8 attributes {itypes = "s", otypes = "s"} {
%alloc = memref.alloc() {name = "X"} : memref<1xi8>
%false = arith.constant false
%0 = arith.cmpi eq, %arg0, %false : i1
scf.if %0 {
%c1_i32 = arith.constant 1 : i32
%2 = arith.trunci %c1_i32 : i32 to i8
affine.store %2, %alloc[0] {to = "X"} : memref<1xi8>
} else {
%c0_i32 = …
```
=> [Builder] Fix incorrect NotOp IR

allo/customize.py, tests/test_schedule_stream.py
1. Add scf ForOp support for dataflow() and pipeline() in customize.py;
2. Add nested loop search support for dataflow() in customize.py
1. Absence of scf ForOp support in some functions.
2. Fail to search the inner loop when it's deeply nested when executing dataflow().
Modify the recursive searching in nested loop.
Provided in the test_schedule_stream.py.
- [√] PR's title starts with a category (e.g. [Bugfix], [IR], [Builder], etc)
- [√] Changes are complete (i.e. I finished coding on this PR)
- [√] All changes have test coverage (It would be better to provide ~2 different test cases to test the robustness of your code)
=> [Bugfix] Add scf ForOp support and nested loop search in dataflow and pipeline

allo/ir/types.py, tests/test_nn.py, tests/test_types.py
This PR adds examples for large bitwidth (#168), although it still cannot be simulated by NumPy. Future direction for this is to leverage numpy structure to simulate large bitwidth integers.
```python
def test_large_bitwidth():
def kernel(a: Int(65536)[1], b: Int(345)[1], c: Int(65536)[1]):
c[0] = a[0] + b[0]
```
```mlir
module {
func.func @kernel(%arg0: i65536, %arg1: i345) -> i65536 attributes {itypes = "ss", otypes = "s"} {
%0 = arith.extsi %arg0 : i65536 to i65537
%1 = arith.extsi %arg1 : i345 to i65537
%2 = arith.addi %0, %1 : i65537
%3 = arith.trunci %2 : i65537 to i65536
return %3 : i65536
}
}
```
=> [Types] Large bitwidth

allo/ir/infer.py, tests/test_builder.py
This PR fixes #170.
```python
def test_size1_array():
def kernel[Ty](X: "Ty[1]"):
a: Ty
def top[Ty](X_buf: "Ty[2, 2, 1]"):
kernel[Ty](X_buf[0, 0])
s = allo.customize(top, instantiate=[int8], verbose=True)
```
```mlir
module {
func.func @kernel(%arg0: memref<1xi8, strided<[1], offset: ?>>) attributes {itypes = "s", otypes = ""} {
%alloc = memref.alloc() {name = "a"} : memref<1xi8>
return
}
func.func @top(%arg0: memref<2x2x1xi8>) attributes {itypes = "s", otypes = ""} {
%c0_i32 = arith.constant 0 : i32
%0 = arith.index_cast %c0_i32 : i32 to index
%c0_i32_0 = arith.constant 0 : i32
%1 = arith.index_cast %c0_i32_0 : i32 to index
%subview = memref.subview %arg0[%0, %1, 0] [1, 1, 1] [1, 1, 1] {from = "X_buf"} : memref<2x2x1xi8> to memref<1xi8, strided<[1], offset: ?>>
call …
```
=> [BugFix] Fix incorrect size-1 array reduction

allo/ir/builder.py, allo/ir/infer.py, tests/test_builder.py
This PR fixes #153. Since MLIR does not provide an integer negation operation, we need to use subtraction `0-x` to achieve the same functionality. One tricky thing is that we need to carefully handle the negation of unsigned integers, which will turn into signed integers.
However, even fixing this, the for loop step cannot be a negative integer, as stated in the MLIR [scf.for](https://mlir.llvm.org/docs/Dialects/SCFDialect/#scffor-scfforop) operation. Therefore, we also don't plan to support negative steps, but directly error out. Otherwise, automatic compiler transformation will make users more confused.
=> [IR] Fix integer negation and negative for loop steps

allo/ir/builder.py, allo/ir/infer.py, allo/ir/use_def.py, allo/ir/utils.py, tests/test_builder.py
This PR fixes #114.
```python
def test_tuple():
def callee(a: float32, b: float32) -> (float32, float32):
c: float32 = a + b
d: float32 = a - b
return c, d
def kernel(A: float32[10], B: float32[10]) -> (float32[10], float32[10]):
C: float32[10] = 0
D: float32[10] = 0
C[i], D[i] = callee(A[i], B[i])
return C, D
np_A = np.random.random((10,)).astype(np.float32)
np_B = np.random.random((10,)).astype(np.float32)
np_C, np_D = mod(np_A, np_B)
np_C_ref = np.zeros((10,), dtype=np.float32)
np_D_ref = np.zeros((10,), dtype=np.float32)
np_C_ref[i], np_D_ref[i] = callee(np_A[i], np_B[i])
np.testing.assert_allclose(np_C, np_C_ref)
np.testing.assert_allclose(np_D, np_D_ref)
```
```mlir
module {
func.func …
```
=> [IR] Add tuple support in use-def chain analysis and type system

.circleci/config.yml, allo/customize.py, allo/dataflow.py, allo/ir/builder.py, allo/ir/infer.py, allo/ir/types.py, tests/dataflow/test_identical_kernel.py, tests/test_nn.py
This PR proposes a new tiled-based programming model in Allo. Check out the following example. It does not contain inter-tile communication.
```python
from allo.ir.types import float32
M, N, K = 32, 32, 32
P0, P1 = 2, 2
Mt, Nt = M // P0, N // P1
def gemm(A: float32[M, K], B: float32[K, N], C: float32[M, N]):
pi, pj = df.get_pid()
for i in range(pi * Mt, (pi + 1) * Mt):
for j in range(pj * Nt, (pj + 1) * Nt):
for k in range(K):
C[i, j] += A[i, k] * B[k, j]
A = np.random.rand(M, K).astype(np.float32)
B = np.random.rand(K, N).astype(np.float32)
C = np.zeros((M, N), dtype=np.float32)
gemm(A, B, C)
np.testing.assert_allclose(C, np.dot(A, B), rtol=1e-5, atol=1e-5)
print("Success!")
```
```mlir
module {
func.func …
```
=> [dataflow][experimental] Add dataflow programming model (tiled kernels)

allo/ir/transform.py, allo/passes.py, tests/test_vhls.py
This PR fixes #154. However, we currently suppose there is only one return argument (the last input). If there are multiple outputs or the output is not the last argument, this PR may still perform incorrectly. To make it fully correct, we need to perform read/write analysis on the buffers, to see which arguments have both read and write access.
```python
def test_csim_write_back():
N = 256
def compute(x: int32[N], y: int32[N]):
for i in range(N):
y[i] = x[i]
s = allo.customize(compute)
if hls.is_available("vitis_hls"):
mod = s.build(target="vitis_hls", mode="csim", project="test.prj")
A = np.random.randint(0, 10, size=(N)).astype(np.int32)
B = np.zeros((N), dtype=np.int32)
mod(A, B)
np.testing.assert_allclose(A, B, rtol=1e-5)
```
```cpp
void compute(
int32_t *v0,
int32_t …
```
=> [backend] Support csim read/write to the same argument

allo/backend/hls.py, allo/dataflow.py, allo/ir/builder.py, allo/ir/infer.py, tests/dataflow/test_producer_consumer.py, tests/test_linalg.py
This PR adds stream type and supports producer-consumer communication patterns.
```python
import allo
from allo.ir.types import float32, Stream
Ty = float32
def producer(A: Ty[M, N]):
pipe: Stream[Ty] = df.pipe(src="producer", dst="consumer")
for i, j in allo.grid(M, N):
out: Ty = A[i, j]
pipe.put(out)
def consumer(B: Ty[M, N]):
pipe: Stream[Ty] = df.pipe(src="producer", dst="consumer")
for i, j in allo.grid(M, N):
data = pipe.get()
B[i, j] = data + 1
A = np.random.rand(M, N).astype(np.float32)
B = np.zeros((M, N), dtype=np.float32)
top = df.build([producer, consumer])
top(A, B)
np.testing.assert_allclose(A + 1, B)
```
```mlir
module {
func.func …
```
=> [dataflow][experimental] Add stream type and support producer-consumer patterns

allo/customize.py, allo/dataflow.py, allo/ir/builder.py, allo/ir/infer.py, allo/ir/use_def.py, allo/ir/utils.py, allo/ir/visitor.py, tests/dataflow/test_no_communication.py, tests/dataflow/test_systolic.py
This PR enhances the composability of dataflow programs. It can now automatically analyze the connection between kernels and generate the correct top-level functions with complex communication patterns (e.g., systolic array).
```python
import allo
from allo.ir.types import float32, Stream
import allo.backend.hls as hls
import pytest
M, N, K = 1, 1, 1
P0, P1 = M + 1, N + 1
def gemm(A: float32[M, K], B: float32[K, N], C: float32[M, N]):
i, j = df.get_pid()
in_A: Stream[float32] = df.pipe(src=(i, j - 1), dst=(i, j))
in_B: Stream[float32] = df.pipe(src=(i - 1, j), dst=(i, j))
out_A: Stream[float32] = df.pipe(src=(i, j), dst=(i, j + 1))
out_B: Stream[float32] = df.pipe(src=(i, j), dst=(i + 1, j))
with allo.meta_if(i == …
```
=> [dataflow][experimental] Support systolic pattern

allo/dataflow.py, allo/ir/infer.py, tests/dataflow/test_tiled_systolic.py, tests/test_template.py
This PR adds a tiled systolic array example to support larger GEMM computation. See `tests/dataflow/test_tiled_systolic.py`. The program has been verified under csim. However, there is still a randomly crashed bug that cannot be easily resolved (#196).
```python
def gemm(A: int32[M, K], B: int32[K, N], C: int32[M, N]):
i, j = df.get_pid()
in_A: Stream[int32] = df.pipe(src=(i, j - 1), dst=(i, j))
in_B: Stream[int32] = df.pipe(src=(i - 1, j), dst=(i, j))
out_A: Stream[int32] = df.pipe(src=(i, j), dst=(i, j + 1))
out_B: Stream[int32] = df.pipe(src=(i, j), dst=(i + 1, j))
for m in range(M // Mt):
for n in range(N // Nt):
with allo.meta_if(i == 0 and j == 0):
pass
with allo.meta_elif(j == 0):
for k in range(K):
out_A.put(A[m * Mt + i - 1, k])
with allo.meta_elif(i …
```
=> [dataflow][experimental] Add tiled systolic array example

allo/ir/builder.py, tests/dataflow/test_cooperative_gemv.py
This PR adds support for 1D mesh mapping and uses cooperative GEMV as an example to demonstrate 1D task partitioning. This is an example pattern on the [Cerebras tutorial](https://sdk.cerebras.net/csl/tutorials/gemv-06-routes-1/) webpage.
```python
@df.kernel(mapping=[P0])
def gemv0(A: Ty[M, N], x: Ty[N]):
pi = df.get_pid()
pipe: Stream[Ty[Mt]] = df.pipe(src="gemv0", dst="gemv1")
y_out: Ty[Mt] = 0
for m in range(pi * Mt, (pi + 1) * Mt):
y_acc: Ty = 0
for n in range(N // 2):
y_acc += A[m, n] * x[n]
y_out[m - pi * Mt] = y_acc
pipe.put(y_out)
@df.kernel(mapping=[P0])
def gemv1(A: Ty[M, N], x: Ty[N], y: Ty[M]):
pi = df.get_pid()
pipe: Stream[Ty[Mt]] = df.pipe(src="gemv0", dst="gemv1")
y_out: Ty[Mt] = 0
for m in range(pi * Mt, (pi + 1) * Mt):
y_acc: Ty = 0
for n in range(N // 2, N):
y_acc += …
```
=> [dataflow][experimental] Support 1D mesh and add cooperative GEMV example

allo/backend/hls.py, allo/backend/report.py, allo/harness/vitis/run.tcl, docs/source/developer/index.rst, docs/source/index.rst, docs/source/setup/index.rst, tutorials/developer_01_ir_builder.py, tutorials/developer_02_mlir.py, tutorials/tutorial_01_get_started.py, tutorials/tutorial_02_vhls.py
As the title mentions, now we can use `s.build(target="vitis_hls", mode="csyn")` to only invoke HLS.
=> [docs][runtime] Update docs and add csyn support to Vitis HLS

allo/backend/hls.py, allo/backend/ip.py, allo/backend/vitis.py, allo/passes.py, tests/test_vhls.py
This PR fixes #217 and #218. The problem does not come from the incorrect codegen but from the incorrect postprocessing of the HLS code.
```python
def test_scalar_not_array():
def top(inst: bool, C: int32[3]):
flag: bool = inst[0]
if flag:
C[0] = C[0] + 1
s = allo.customize(top)
mod = s.build(target="vitis_hls", mode="csim", project="test_scalar.prj")
assert "bool v0," in mod.hls_code and ",," not in mod.hls_code
if hls.is_available("vitis_hls"):
C = np.array([1, 2, 3], dtype=np.int32)
mod(1, C)
np.testing.assert_allclose(C, [2, 2, 3], rtol=1e-5)
```
=> [Backend] Fix scalar interface in HLS

allo/backend/hls.py, allo/backend/vitis.py, tutorials/tutorial_02_vhls.py
This PR fixes #162. It adds support to streamline the bitstream execution process from Python. Now users can directly pass in Numpy array and call the module/bitstream just like what they do for software testing.
This PR also fixes a bug of passing in scalars in the host code (related to #219).
```python
import allo
from allo.ir.types import bool, int32
def test_scalar_not_array():
def top(inst: bool, C: int32[3]):
flag: bool = inst[0]
if flag:
C[0] = C[0] + 1
s = allo.customize(top)
mod = s.build(target="vitis_hls", mode="hw", project="test_scalar.prj")
C = np.array([1, 2, 3], dtype=np.int32)
mod(1, C)
np.testing.assert_allclose(C, [2, 2, 3], rtol=1e-5)
test_scalar_not_array()
```
=> [Backend][Docs] Update Vitis HLS host code to support load/store data from/to files

allo/ir/builder.py, allo/ir/infer.py, allo/ir/use_def.py, mlir/include/allo/Dialect/Visitor.h, mlir/lib/Translation/EmitVivadoHLS.cpp, tests/test_builder.py
This PR adds min/max builtin function support.
```python
@pytest.mark.parametrize("T", [int8, int32, float32])
def test_minmax(T):
def kernel(A: T[10]) -> (T[2], T[2]):
min_val: T[2] = 0x3F3F3F3F
max_val: T[2] = -0x3F3F3F3F
min_val[0] = min(min_val[0], A[i])
max_val[0] = max(max_val[0], A[i])
return min_val, max_val
if T == int8:
np_A = np.random.randint(-64, 64, size=(10,)).astype(np.int8)
elif T == int32:
np_A = np.random.randint(-1000, 1000, size=(10,)).astype(np.int32)
elif T == float32:
np_A = np.random.random((10,)).astype(np.float32)
allo_min, allo_max = mod(np_A)
assert allo_min[0] == np.min(np_A)
assert allo_max[0] == np.max(np_A)
mod = s.build(target="vhls")
assert "min" in mod.hls_code
assert "max" …
```
=> [IR] Support max/min functions

allo/ir/builder.py, allo/ir/utils.py, mlir/lib/Translation/EmitIntelHLS.cpp, mlir/lib/Translation/EmitVivadoHLS.cpp, tests/test_builder.py, tests/test_vhls.py
Previously Allo implemented scalar as size-1 rank-1 memref to avoid the limitation of the Python binding, but this introduced lots of problems when lowering to the HLS backend. As we have already updated to the latest LLVM, we can construct the correct rank-0 memref at the Python level to resolve this issue.
This corresponding HLS codegen also needs to be changed. Now only rank-0 memref will be generated as scalar.
```python
def test_scalar():
def kernel() -> int32:
a: int32 = 0
b: int32 = a + 1
return b
assert "%alloc[]" in str(s.module)
assert mod() == 1
mod = s.build(target="vhls")
assert "," not in mod.hls_code
```
```mlir
module {
func.func @kernel() -> i32 attributes {itypes = "", otypes = "s"} {
%alloc = memref.alloc() …
```
=> [IR] Implement scalar as rank-0 memref

allo/ir/builder.py, allo/ir/infer.py, allo/ir/typing_rule.py, mlir/lib/Translation/Utils.cpp, tests/test_builder.py
This PR adds casting operations for min/max/put. Specifically, the codegen for constant float values of HLS also changed, since `0.0` will be interpreted as double if not explicitly declaring the type.
```python
def test_minmax_cast():
def kernel(A: int8[2]) -> int32[2]:
res: int32[2] = 0
res[0] = min(A[0], 0)
res[1] = max(A[1], 0.0)
return res
np_A = np.random.randint(-64, 64, size=(2,)).astype(np.int8)
allo_B = mod(np_A)
assert allo_B[0] == min(np_A[0], 0)
assert allo_B[1] == max(np_A[1], 0.0)
mod = s.build(target="vhls")
print(mod)
assert "min" in mod.hls_code
assert "max" in mod.hls_code
assert "(float)" in mod.hls_code
```
```cpp
void kernel(
int8_t v0[2],
int32_t v1[2]
) {     // L2
for (int v2 = 0; v2 < 2; v2++) {      // …
```
=> [IR] Add casting for min/max/put

tests/dataflow/test_1D_systolic.py, tests/dataflow/test_Smith_Waterman_systolic.py, tests/dataflow/test_smith_waterman_systolic.py
This PR adds examples of using dataflow to implement 1D Systolic GEMM and 2D Systolic Smith-Waterman algorithm
`python3 python3 test_Smith_Waterman_systolic.py ` and ` python3 test_1D_systolic.py` should output `Passed!`
=> [Dataflow] Add 1D Systolic GEMM and 2D Systolic Smith-Waterman algorithm

tests/dataflow/test_unified_systolic.py
The implementation of unified systolic array to achieve GEMM with output-stationary or weight-stationary dataflow.
Numpy tests are included.
=> [dataflow] Unified Systolic Array

allo/dataflow.py, docs/source/developer/index.rst, docs/source/setup/index.rst, tests/dataflow/test_tiled_systolic.py
This PR exposes the build target in the `df.build` function as follows:
```python
mod = df.build(gemm, target="vitis_hls", mode="csyn", project="top.prj")
```
so users can now directly generate the corresponding hardware design from a dataflow program.
Some documentations are also updated in this PR.
=> [dataflow] Expose build target in df.build function

allo/ir/builder.py, tests/test_types.py
This PR introduces expanding support for casting between `Index`, `Fixed`, and `UFixed` types in the Allo IR. This enhancement allows for seamless conversions between these types, which broadens the flexibility of type handling in the IR layer.
Previously, the Allo IR lacked direct support for conversions between `Index` and `Fixed/UFixed` types, limiting the flexibility in scenarios where such conversions are needed for operations. Attempting these conversions required workarounds or was unsupported, creating friction in code requiring dynamic type handling.
- Added `Index <-> Fixed/UFixed` single-step conversions in the `cast_map` within `ASTTransformer`.
- Implemented new casting operations `IntToFixedOp` and `FixedToIntOp` as intermediary conversions to facilitate direct type …
=> [Builder] Add `index` from/to `Float`/`Fixed`/`UFixed` type casting

allo/ir/builder.py, allo/ir/typing_rule.py, mlir/include/allo/Dialect/AlloOps.td, mlir/include/allo/Dialect/Visitor.h, mlir/lib/Conversion/FixedPointToInteger.cpp, mlir/lib/Translation/EmitVivadoHLS.cpp, tests/test_types.py
This PR tries to fix #241 by adding new shifting operations for fixed types. Reference example comes from the official [documentation](https://docs.amd.com/r/en-US/ug1399-vitis-hls/Class-Methods-Operators-and-Data-Members) of `ap_int`.
```python
def test_fixed_shift():
def kernel(A: Fixed(8, 3)[2]) -> float32[2]:
shl: Fixed(25, 10) = A[0] << 2
shr: Fixed(25, 10) = A[1] >> 2
res: float32[2] = 0.0
res[0] = float(shl)
res[1] = float(shr)
return res
A = np.array([5.375, 5.375], dtype=np.float32)
np.testing.assert_allclose(mod(A), [-10.5, 1.25], rtol=1e-5)
```
```mlir
module {
func.func @kernel(%arg0: memref<2x!allo.Fixed<8, 3>>) -> memref<2xf32> attributes {itypes = "s", otypes = "_"} {
%0 = affine.load %arg0[0] {from = "A"} : …
```
=> [IR] Add shift left/right operations for fixed points

allo/backend/aie.py, tests/dataflow/test_vector_vector.py
This PR adds examples on vector add/mul on Ryzen NPU.
```python
def _test_vector_vector_mul():
Ty = float32
M = 1024
def core(A: Ty[M], B: Ty[M], C: Ty[M]):
for i in range(M):
C[i] = A[i] * B[i]
top = df.build(core, target="aie")
A = np.random.random(M).astype(np.float32)
B = np.random.random(M).astype(np.float32)
C = np.zeros(M).astype(np.float32)
top(A, B, C)
np.testing.assert_allclose(C, A * B, rtol=1e-5)
print("PASSED!")
```
```mlir
module {
aie.device(npu1_1col) {
%tile_shim = aie.tile(0, 0)
%tile_mem = aie.tile(0, 1)
%tile_comp = aie.tile(0, 2)
aie.objectfifo @in_sh0(%tile_shim, {%tile_mem}, 2 : i32) : !aie.objectfifo<memref<1024xf32>>
aie.objectfifo @in0(%tile_mem, {%tile_comp}, 2 : i32) : !aie.objectfifo<memref<1024xf32>>
aie.objectfifo.link [@in_sh0] -> …
```
=> [Backend][AIE] Add vector support for AIE

allo/backend/hls.py, allo/backend/vitis.py, allo/frontend/pytorch.py, examples/torch/toy.py
This PR adds the following two features:
1. Dump input data to file so Vitis on-board execution can directly read from files without recompiling the host program.
2. Expose Vitis target to the Pytorch frontend, so users can specify the `target` to build the hardware design.
=> [Backend][Vitis] Fix Vitis input data and expose target to pytorch frontend

allo/dataflow.py, allo/ir/builder.py, allo/ir/infer.py, allo/ir/types.py, mlir/include/allo-c/Dialect/AlloTypes.h, mlir/include/allo/Dialect/AlloOps.td, mlir/include/allo/Dialect/AlloTypes.td, mlir/include/allo/Dialect/Visitor.h, mlir/lib/Bindings/AlloTypes.cpp, mlir/lib/CAPI/Dialect/AlloTypes.cpp, mlir/lib/Translation/EmitVivadoHLS.cpp, tests/dataflow/test_producer_consumer.py
This PR adds an explicit stream type (`stream<T>`) in the Allo-MLIR dialect to replace the original memref implementation. Specifically, three operations are added:
1. `allo.stream_construct()`: Create a new stream object
2. `allo.stream_get(%stream)`: Get data from a stream
3. `allo.stream_put(%stream, %data)`: Put data into a stream
The dataflow interface uses these operations to construct the IR. Now it can support declaring an array in a stream, which may be useful for DMA transmission. Also, we added codengen support to the HLS backend to generate these operations using `hls::stream`
```mlir
module {
func.func @producer_0(%arg0: memref<16x16xf32>, %arg1: !allo.stream<f32, 2>) attributes {stypes = "_g"} {
affine.for %arg2 = 0 to 16 {
affine.for %arg3 = 0 to 16 {
%0 = affine.load …
```
=> [IR][dataflow] Add explicit stream type in MLIR

tests/dataflow/test_smith_waterman_systolic.py, tests/dataflow/test_weight_stationary_gemm.py
This PR adds weight stationary systolic gemm and fix Smith-Waterman leftover data issue
The previous approach for Smith-Waterman used systolic array did not handle leftover data, which created problems in synthesis.
Add drains to handle leftover data.
=> [dataflow] Add weight stationary systolic gemm and fix Smith-Waterman leftover data issue

allo/dataflow.py, tests/dataflow/test_mlp.py
This PR exposes the `customize` interface to the dataflow programs, so users can leverage the dataflow interface with the decoupled customizations at the same time. A three-layer MLP example is also provided.
```python
@df.region()
def top():
...
s = df.customize(top)
s.pipeline("linear1_0:j")
mod = s.build(target="vitis_hls", mode="hw", project="df-mlp3-relu-on-chip.prj")
```
=> [dataflow] Expose customize interface

.gitignore, allo/backend/hls.py, allo/dataflow.py, allo/passes.py, tests/dataflow/test_mlp.py, tests/dataflow/test_wrap_movement.py, tests/pytorch/test_linear.py, tests/test_unify.py, tests/test_utils.py, tests/test_vhls.py
This PR fixes the issue of incorrect dataflow construction introduced by #263. Specifically, we need to analyze the arguments in the top-level function and check whether they have read/write operations. This is done by a sequential traversal of the IR through the `FuncOp`.
```python
def kernel(A: int32[32], B: int32[32], C: int32[32]):
for i in range(32):
C[i] = A[i] + B[i]
def rw_kernel(D: int32[32]):
for i in range(32):
D[i] = D[i] + 1
def top2(A: int32[32], B: int32[32], C: int32[32], D: int32[32]):
kernel(A, B, C)
write_kernel(A)
rw_kernel(D)
s = allo.customize(top2)
res = analyze_arg_load_store(s.module)
```
```
{'kernel': ['in', 'in', 'out'], 'write_kernel': ['out'], 'rw_kernel': ['both'], 'top2': ['both', 'in', 'out', 'both']}
```
=> [dataflow][backend] Add IO analysis pass

allo/ir/builder.py, allo/ir/infer.py, allo/ir/use_def.py, allo/ir/visitor.py, tests/dataflow/test_daisy_chain_gemm.py, tests/test_template.py
This PR fixes the dangling `meta_if` matching issue. Previously, each `meta_if` needs to be accompanied with a `meta_else`. Otherwise, different levels of `meta_if/else` will mix together causing problems.
For example, in the following case, according to the Python convention, the second `meta_else` should match the first `meta_if` based on indention.
```python
with allo.meta_if(...):
with allo.meta_if(...):
...
with allo.meta_else():
...
```
=> [IR] Fix dangling meta_if matching

allo/customize.py, allo/ir/builder.py, allo/ir/infer.py, allo/ir/utils.py, allo/ir/visitor.py, allo/logging.py, requirements.txt, tests/test_builder.py, tests/test_linalg.py, tests/test_utils.py
The current Allo implementation does not trace back to the source kernel when encountering an error, which only shows the Python traceback inside the IR builder, making debugging extremely hard. This PR adds traceback to the Allo kernel source code, enabling better error identification and debugging.
```python
def kernel(A: int32[32]):
B: undefined_type = 1
def kernel2(A: int32[32]):
kernel(A)
s = allo.customize(kernel2)
```
The following traceback does not only give the error inside the builder/visitor, but also gives the error from the source code.
```
Traceback (most recent call last):
File "/scratch/users/hc676/allo/allo/ir/infer.py", line 1093, in visit_stmts
results.append(visit_stmt(ctx, stmt))
^^^^^^^^^^^^^^^^^^^^^
File "/scratch/users/hc676/allo/allo/ir/visitor.py", line 122, in …
```
=> [debug] Support source code error traceback

allo/ir/transform.py, allo/passes.py
When #263 wraps the data loading/storing logic as a function, it does not attach the layout (whether a buffer is partitioned or not) to its function argument and definition, causing the buffer mismatch issue. This PR explicitly attaches the layout to the memref to resolve this issue.
```python
import allo
from allo.ir.types import float32
concrete_type, L, D, O = float32, 1024, 1024, 1024
def kernel_linear_layer[Ty, L, D, O](X: "Ty[L, D]", W: "Ty[D, O]", B: "Ty[O]", Z: "Ty[L, O]"):
for i, j in allo.grid(L, O, name="linear_compute"):
Z[i, j] = B[j]
for k in allo.reduction(D, name="inner_prod"):
Z[i, j] += X[i, k] * W[k, j]
s_linear = allo.customize(kernel_linear_layer, instantiate=[concrete_type, L, D, O] )
s_linear.partition(s_linear.X, partition_type=2, dim=2, factor=32) …
```
=> [Pass] Fix load/store data from/to a partitioned buffer in top-level

allo/customize.py
=> [Bugfix] Fix starting_line_no for PyTorch frontend

allo/backend/config.py, allo/backend/hls.py, allo/backend/vitis.py, allo/customize.py, allo/dataflow.py, tests/test_vhls.py
This PR fixes #274. Users can now specify the target device and frequency by passing in additional configuration in the build function:
```python
s.build(target="vitis_hls", configs={"device": "u250", "frequency": 300})
```
This PR also includes the Intel HLS backend (#206) with the updated LLVM.
=> [Backend] Support specifying target device and frequency

allo/backend/hls.py, allo/customize.py, allo/dataflow.py, allo/passes.py, tests/dataflow/test_daisy_chain_gemm.py, tests/dataflow/test_multi_cache_gemm.py, tests/dataflow/test_tiled_systolic.py, tests/dataflow/test_wrap_movement.py
This PR has three primary contributions as follows:
1. Modify the automated buffer-generation as optional pass for users.
2. Enhance the multi-cache design with a stream-type L3 for tiling.
3. Polish some naming and testcases.
Under expected conditions, this multi-cache design can significantly enhance performance and enable large-scale computation. 
Examples are provided inside.
Although the passed csim tests prove the functionality of architecture, there are some notable minor issues:
1. The design contains data-packing technique to improve the efficiency of memory access, but the relevant type system is not well-supported, including efficient data packaging in pythonish testing and type consistency between generated hls code and test inputs. Relevant utility functions are neccessary to …
=> [dataflow] [Pass] Enable multi-cache design for larger-scale gemm

allo/dataflow.py, tests/dataflow/test_daisy_chain_gemm.py, tests/dataflow/test_unified_systolic.py
This PR supplemented, refined, and organized several designs of unified systolic array, including:
1. `unified_gemm_simple`: simple unified array achieving GEMM, similar to the one in Gemmini;
2. `unified_gemm_tiling`: enabling GEMM tiling, which means the array size can be decoupled from the input dimensions;
3. `unified_gemm_daisy_chain`: non-instructional inputs are also transmitted in a daisy-chain manner, reducing simultaneous access to the array.
Also take this opportunity to provide a comparative explanation of other dataflow array designs:
1. [systolic](https://github.com/cornell-zhang/allo/blob/main/tests/dataflow/test_systolic.py): simple output-stationary array;
2. [systolic_daisy_chain](https://github.com/cornell-zhang/allo/blob/main/tests/dataflow/test_daisy_chain_gemm.py): …
=> [dataflow] Supplement, refine, and organize designs of unified systolic array

allo/ir/builder.py, mlir/lib/Translation/EmitVivadoHLS.cpp, tests/test_types.py
This PR attaches the missing unsigned attributes to the MLIR operations in order to preserve the signedness when generating the backend HLS code.
```python
def casting():
buf1: UInt(15)[16, 16] = 0
buf2: float32[16, 16]
for i, j in allo.grid(16, 16):
buf2[i, j] = float(buf1[i, j] + buf1[j, i])
s = allo.customize(casting)
code = s.build(target="vhls")
print(code)
```
```cpp
void casting(
) {     // L2
ap_uint<15> buf1[16][16];     // L5
for (int v1 = 0; v1 < 16; v1++) {     // L6
for (int v2 = 0; v2 < 16; v2++) {   // L6
buf1[v1][v2] = 0; // L6
}
}
float buf2[16][16];   // L7
l_S_i_j_0_i: for (int i = 0; i < 16; i++) {   // L8
l_j: for (int j = 0; j < 16; j++) { // L9
ap_uint<15> v6 = buf1[i][j];      // L10
ap_uint<15> v7 = buf1[j][i];      // L11
uint16_t v8 = v6; // L12 …
```
=> [IR] Attach uint attributes

allo/ir/builder.py, allo/ir/infer.py, mlir/lib/Translation/EmitTapaHLS.cpp, mlir/lib/Translation/EmitVivadoHLS.cpp, tests/test_bitop.py
This PR exposes the bitcast operation to the frontend (which has already been added in MLIR previously). The API is just `.bitcast()`. By default, if `.bitcast()` is operated on an integer, it will be cast to a floating point; while `.bitcast()` is operated on a floating point, it will be cast to an integer with the same bitwidth. Notice this is different from a normal cast, where a normal cast preserves the actual value of the variable, while bitcast preserves the bits.
```python
def test_bitcast_uint2float():
def kernel(A: uint32[10, 10]) -> float32[10, 10]:
B: float32[10, 10]
for i, j in allo.grid(10, 10):
B[i, j] = A[i, j].bitcast()
return B
A_np = np.random.randint(100, size=(10, 10)).astype(np.uint32)
B_np = mod(A_np)
answer …
```
=> [IR] Add bitcast operation

allo/backend/llvm.py, allo/utils.py, mlir/lib/Translation/EmitTapaHLS.cpp, mlir/lib/Translation/EmitVivadoHLS.cpp, tests/test_bitop.py, tests/test_types.py
This PR adds fp16 support for both LLVM and HLS backend. The LLVM backend needs to first represent the float16 value in int16, and the HLS backend uses `half` to represent fp16.
```python
def test_fp16_array():
def kernel(A: float16[10]) -> float16[10]:
B: float16[10]
B[i] = A[i] + 1
return B
assert "f16" in str(s.module)
A = np.random.rand(10).astype(np.float16)
B = mod(A)
np.testing.assert_allclose(B, A + 1, rtol=1e-5)
```
=> [Type][Backend] Support fp16

allo/backend/aie.py, allo/backend/llvm.py, allo/dataflow.py, allo/dsl.py, allo/ir/builder.py, allo/ir/infer.py, allo/utils.py, tests/dataflow/aie/test_gemm.py, tests/dataflow/aie/test_matrix.py, tests/dataflow/aie/test_multi_core.py, tests/dataflow/aie/test_vector.py
The original AIE backend with dataflow interface only support simple element-wise application, like vector add. It used local indexing, which is insufficient for more complex tensor access pattern, like matrix multiplication. 
In the original AIE interface, the compiler lacks sufficient information to determine which dimension (M, K, or N) should be used for tiling in this GEMM implementation.
```
Ty = int32
P0 = 1
Mt = M // P0
@df.region()
def top():
@df.kernel(mapping=[P0])
def gemm(A: Ty[M, K], B: Ty[K, N], C: Ty[M, N]):
for i, j, k in allo.grid(Mt, K, N):
C[i, j] += A[i, k] * B[k, j]
```
In the new interface, we adopt global indexing similar to the HLS backend for AIE. Additionally, we leverage tensor slicing access, inspired by Triton, to enable the compiler to …
=> [Backend][AIE] Support global indexing, tensor access and kernel reindex for AIE kernel mapping

allo/backend/llvm.py, allo/customize.py, allo/frontend/pytorch.py, allo/ir/builder.py, allo/ir/infer.py, allo/library/__init__.py, allo/library/nn.py, examples/torch/mlp.py, tests/test_nn.py
This PR automatically dispatches PyTorch operations to Allo kernels and applies pre-defined schedules.
```python
import torch
import torch.nn.functional as F
import torch.nn as nn
import allo
class MLP(nn.Module):
def __init__(self):
super().__init__()
self.linear1 = torch.nn.Linear(16, 32)  # 8*16 * 32*16
self.linear2 = torch.nn.Linear(32, 10)
def forward(self, data):
out = self.linear1(data)
out = self.linear2(out)
out = F.relu(out)
return out
model = MLP()
model.eval()
example_inputs = [torch.rand(8, 16)]
llvm_mod = allo.frontend.from_pytorch(
model, example_inputs=example_inputs, verbose=True
)
golden = model(*example_inputs)
np_inputs = [x.detach().numpy() for x in example_inputs]
res = llvm_mod(*np_inputs)
torch.testing.assert_close(res, golden.detach().numpy())
``` …
=> [Frontend] Support auto schedule composition for PyTorch models

allo/backend/aie.py, allo/backend/llvm.py, allo/dataflow.py, tests/dataflow/aie/test_gemm.py
This PR adds support for 2D mappings in AIE kernels along with the corresponding allocation strategy. It also enables multiple kernels within a single region and provides backend support for each kernel.
```
from allo.ir.types import int32
import allo
Ty = int32
P0, P1 = 2, 2
Mt, Nt = M // P0, N // P1
@df.region()
def top():
def gemm(A: Ty[M, K], B: Ty[K, N], C: Ty[M, N]):
p0, p1 = df.get_pid()
C[p0 * Mt : (p0 + 1) * Mt, p1 * Nt : (p1 + 1) * Nt] = allo.matmul(
A[p0 * Mt : (p0 + 1) * Mt, :], B[:, p1 * Nt : (p1 + 1) * Nt]
)
mod = df.build(top, target="aie")
A = np.random.randint(0, 64, (M, K)).astype(np.int32)
B = np.random.randint(0, 64, (K, N)).astype(np.int32)
C = np.zeros((M, …
```
=> [Backend][AIE] Support 2D mappings and multiple kernels within one region

allo/backend/aie.py, allo/backend/llvm.py, allo/dataflow.py, allo/ir/builder.py
This PR introduces support for building the AIE backend without relying on the tensor dialect. This enables top function construction and optimization for operation fusion. Users can select between tensor dialect-based and memref dialect-based building using the `enable_tensor` option.
```python
from allo.ir.types import int32
import allo
Ty = int32
P0, P1 = 2, 2
Mt, Nt = M // P0, N // P1
@df.region()
def top():
def gemm(A: Ty[M, K], B: Ty[K, N], C: Ty[M, N]):
p0, p1 = df.get_pid()
C[p0 * Mt : (p0 + 1) * Mt, p1 * Nt : (p1 + 1) * Nt] = allo.matmul(
A[p0 * Mt : (p0 + 1) * Mt, :], B[:, p1 * Nt : (p1 + 1) * Nt]
)
mod = df.build(top, target="aie", enable_tensor=False)
A = np.random.randint(0, 64, …
```
=> [Backend][AIE] Support pure memref builder for AIE backend

allo/passes.py, tests/test_canonicalization.py
This PR is the first of many for an autoscheduling optimization (https://github.com/cornell-zhang/allo/discussions/297) outlined in the stream-hls paper that implements preprocessing of reduction loops. 
Legal conversion of shared buffers to FIFO requires that the number of writes to the shared buffer equals the number of reads. Below is a violation of this condition, where matrix C is written to $8^3$ times, while only read from $8^2$ times. 
```python
def matmul_addition() -> float32[8, 8]:
A: float32[8, 8] = 1.0
B: float32[8, 8] = 2.0
C: float32[8, 8] = 0.0
D: float32[8, 8] = 3.0
for i in range(8):
for j in range(8):
for k in range(8):
C[i, j] = C[i, j] + A[i, k] * B[k, j]
E: float32[8, 8]
for i in range(8):
for j in range(8):
E[i, j] = C[i, j] + D[i, j]
return E
```
The pass works in …
=> [Pass] Preprocess Reduction Loops

allo/backend/llvm.py, allo/backend/vitis.py, allo/ir/builder.py, allo/ir/infer.py, allo/ir/types.py, allo/ir/typing_rule.py, allo/utils.py, requirements.txt, tests/test_types.py, tutorials/dive_01_data_types.py
This PR adds bfloat16 support which will be used in the AIE backend. The NumPy support is via [ml_dtypes](https://github.com/jax-ml/ml_dtypes).
Now we need to explicitly specify the fractional bits of the floating point types, specifically `Float(16, 10)` represents `float16` while `Float(16, 7)` represents `bfloat16`.
```python
def test_bf16_array():
def kernel(A: bfloat16[10]) -> bfloat16[10]:
B: bfloat16[10]
B[i] = A[i] + 1
return B
assert "bf16" in str(s.module)
A = np.random.rand(10).astype(ml_dtypes.bfloat16)
B = mod(A)
np.testing.assert_allclose(
B.astype(np.float32), (A + 1).astype(np.float32), rtol=1e-5
)
```
=> [Types] Add bfloat16

allo/backend/aie.py, allo/backend/aie_kernels/add.cc, tests/dataflow/aie/test_vector.py
This PR adds support for incorporating vectorized kernels in the AIE backend.
```python
def _test_vector_vector_add():
Ty = int32
M = 1024
@df.region()
def top():
def core(A: Ty[M], B: Ty[M], C: Ty[M]):
C[:] = allo.add(A, B)
mod = df.build(top, target="aie")
A = np.random.randint(0, 100, M).astype(np.int32)
B = np.random.randint(0, 100, M).astype(np.int32)
C = np.zeros(M).astype(np.int32)
mod(A, B, C)
np.testing.assert_allclose(C, A + B)
print("PASSED!")
```
See the generated private function and the `func.call` function below.
```mlir
module {
aie.device(npu1_2col) {
func.func private @eltwise_add_i32_vector(memref<1024xi32>, memref<1024xi32>, memref<1024xi32>)
%tile_shim = aie.tile(0, 0)
%tile_mem0 = aie.tile(0, 1)
%tile_mem1 = aie.tile(1, 1)
%tile_comp_core_0 = …
```
=> [Backend][AIE] Support external vectorized kernels

allo/backend/aie.py, allo/dataflow.py, allo/utils.py, tests/dataflow/aie/test_producer_consumer.py
This PR supports fifo created by `df.pipe` in AIE backend. It also support multi-kernel communication patterns like producer-consumer case.
```python
Ty = int32
@df.region()
def top():
pipe = df.pipe(dtype=Ty, shape=(), depth=4)
def producer(A: Ty[M, N]):
for i, j in allo.grid(M, N):
out: Ty = A[i, j]
pipe.put(out)
def consumer(B: Ty[M, N]):
for i, j in allo.grid(M, N):
data = pipe.get()
B[i, j] = data + 1
```
```mlir
module {
aie.device(npu1_1col) {
%tile_shim = aie.tile(0, 0)
%tile_mem0 = aie.tile(0, 1)
%tile_comp_producer_0 = aie.tile(0, 2)
%tile_comp_producer_0_buf0 = aie.buffer(%tile_comp_producer_0) : memref<i32>
%tile_comp_consumer_0 = aie.tile(0, 3)
aie.objectfifo @in_sh_producer_a0(%tile_shim, {%tile_mem0}, 2 : …
```
=> [Backend][AIE] Support fifo and multi-kernel communication for AIE backend

allo/autoscheduler/dfg.py, allo/autoscheduler/passes.py, allo/autoscheduler/util.py, tests/test_canonicalization.py, tests/test_dfg.py
Parses a MLIR module into a dataflow graph for autoscheduler analysis (https://github.com/cornell-zhang/allo/discussions/297)
MLIR module can now be parsed into a dataflow graph. Each node in the graph represents an affine kernel and is annotated with information regarding the access pattern, achievable II, relative first/last read/write times for each possible loop permutation of the affine kernel. An approximate DSP factor for the affine kernel is also computed. This information will be used to build the performance model described in stream-hls. 
DFG implementation also includes printing to dotgraph format for easy debugging. 
The 3-Matmul example 
```python
def three_mm(A: int32[8, 8], B: int32[8, 8], C: int32[8, 8], D: int32[8, 8]) -> int32[8, 8]:
E: int32[8, 8] = matrix_multiply(A, …
```
=> [Dataflow] DFG Implementation

allo/backend/simulator.py, tests/dataflow/aie/test_gemm.py, tests/dataflow/aie/test_matrix.py, tests/dataflow/aie/test_multi_core.py, tests/dataflow/aie/test_producer_consumer.py, tests/dataflow/aie/test_vector.py
This PR adds linalg dialect lowering passes to the pipeline of dataflow simulator, so that AIE kernels can be simulated.
Tests of dataflow simulator are added to all testcases under `tests/dataflow/aie/`.
=> [Simulator][Dataflow] Support simulating AIE kernels

allo/ir/builder.py, allo/ir/infer.py, tests/test_builder.py
Fixes #322 
This PR fixes type inference rules for functions in `allo.dsl`, which can be handled as general binary ops with shape broadcasting.
=> Fix allo.dsl typing rules

allo/ir/builder.py, docs/source/setup/index.rst, mlir/lib/Translation/EmitVivadoHLS.cpp
This PR fixes the hash values when creating constant values. Previously it may have variable names like `const_-34312`, which is because the hash values can be negative numbers. This PR adds `abs` to it.
Additionally, softmax function call in HLS is also fixed. As its last argument is also the return, no additional variable needs to be created.
```
===>The following messages were generated while  performing high-level synthesis for kernel: forward Log file: /home/sumin/allo/examples/torch/gpt2/_x.hw.xilinx_u280_gen3x16_xdma_1_202211_1/forward/forward/vitis_hls.log :
ERROR: [v++ 207-2492] default initialization of an object of const type 'const int64_t' (aka 'const long') (/home/sumin/allo/examples/torch/gpt2/kernel.cpp:156:15)
ERROR: [v++ 207-1263] expected ';' after top level declarator …
```
=> [Backend] Fix hash constants and softmax

allo/autoscheduler/dfg.py, requirements.txt, tests/autoscheduler/test_autoscheduler.py
Implements the graph-level pipelining MINLP formulation from Stream-HLS. Future PRs will build on this one to extract the schedule from the optimal MINLP solution. 
Note that larger test cases are disabled in Github actions since it is not known how to add a gurobi license to that environment at this time. 
For this simple sanity check case, the optimal solution of the MINLP should involve either the first loop nest or the second loop nest being permuted. 
```python
def simple() -> int32[10, 10]:
A: int32[10, 10]
B: int32[10, 10]
for j in range(10):
A[i, j] = i + j
for j in range(10):
B[i, j] = A[i, j] + 1
return B
```
produces the following model 
```lp
\ Model graph_parallelism_performance_model
\ LP format - for model browsing. Use MPS format to …
```
=> [Autoscheduler] Implement MINLP for Graph Parallelism Model

allo/autoscheduler/dfg.py, allo/autoscheduler/outline_loops.mlir, allo/autoscheduler/passes.py, allo/autoscheduler/primitives.py, allo/autoscheduler/util.py, allo/ir/transform.py, examples/polybench/gesummv.py, tests/autoscheduler/test_autoscheduler.py, tests/autoscheduler/test_dfg.py, tests/autoscheduler/test_passes.py
This Autoscheduler (https://github.com/cornell-zhang/allo/discussions/297) PR implements the functionality for extracting the schedule from the MINLP solution and applying the schedule primitives.
This PR also includes some bug fixes and improvements to `dfg.py`
The allo.verify() check is currently disabled by default and the correctness of output schedule is not guaranteed. 
In the simple example 
```python
def simple() -> int32[10, 10]:
def stageA() -> int32[10, 10]:
A: int32[10, 10]
for j in range(10):
A[i, j] = i + j
return A
def stageB(A: int32[10, 10]) -> int32[10, 10]:
B: int32[10, 10]
for j in range(10):
B[i, j] = A[i, j] + 1
return B
A = stageA()
B = stageB(A)
return B
```
after solving and extracting the schedule, we get the following …
=> [Autoscheduler] Extract schedule from MINLP solution

allo/backend/aie.py, tests/dataflow/aie/test_pingpong_gemm.py
This PR resolves the TODO from [#341](https://github.com/cornell-zhang/allo/pull/341).
In the original compute tile placement strategy for the 2×2×2 cooperative GEMM, four compute tiles require three DMA-in channels to receive data — two for input tensors A and B, and one for the `pipe` stream. However, each AIE tile supports only two DMA-in channels, which leads to a DMA resource conflict and compilation error.
Under the previous strategy, the `pipe` stream communication spanned two hops (e.g., from tile_0_2 to tile_2_2). According to AMD documentation ([link](https://docs.amd.com/r/en-US/am009-versal-ai-engine/AI-Engine-Tile-to-AI-Engine-Tile-Data-Communication-via-Memory-and-DMA)), communication between non-adjacent tiles must use DMA, further exacerbating the issue.
This PR introduces …
=> [Dataflow][AIE] Understand the communication pattern between AIE tiles and support 2x2x2 cooperative GEMM by using different compute tiles placement

allo/dataflow.py, allo/ir/builder.py, allo/ir/utils.py, tests/dataflow/test_df_unit.py
This PR fixes #342. It supports nested functions in the dataflow region. The dataflow functions are labeled as `df.kernel` using attributes.
```python
def test_func_index():
Ty = float32
M, N = 4, 4
def index_calculation(x: index) -> index:
res: index = x - 1
return res
@df.region()
def top():
pipe = df.pipe(dtype=Ty, shape=(), depth=4)
def producer(A: Ty[M, N]):
for i, j in allo.grid(M, N):
out: Ty = A[i, index_calculation(j) + 1]
pipe.put(out)
def consumer(B: Ty[M, N]):
for i, j in allo.grid(M, N):
data = pipe.get()
B[i, j] = data + 1
A = np.random.rand(M, N).astype(np.float32)
B = np.zeros((M, N), dtype=np.float32)
sim_mod = df.build(top, target="simulator")
sim_mod(A, B)
np.testing.assert_allclose(A + 1, B)
```
Please …
=> [Dataflow] Support function calls in dataflow region

allo/ir/builder.py, allo/ir/infer.py, allo/template.py, tests/dataflow/aie/test_tp.py, tests/test_template.py
This PR introduces a new metaprogramming primitive `allo.meta_for` for compile-time loop unrolling, which is useful for some cases that require compile-time constant values (e.g., FIFO array indices). This PR fixes #325.
```python
def test_meta_for():
N = 8
def top(A: int32[N]):
with allo.meta_for(0, N) as i:
A[i] = A[i] + 1
with allo.meta_for(N) as i:
A[i] = A[i] - 1
with allo.meta_for(N - 1, N, 2) as i:
with allo.meta_if(i == N - 1):
A[i] = A[i] + 3
with allo.meta_for(N + 1, N, 1) as i:
A[i] = A[i] * 2
s = allo.customize(top)
np_A = np.random.randint(0, 10, N).astype(np.int32)
np_golden = np_A.copy()
np_golden[-1] += 3
mod(np_A)
np.testing.assert_allclose(np_A, np_golden, rtol=1e-4, atol=1e-4)
```
We can see from the MLIR module that the loop body is …
=> [Template] Add allo.meta_for for compile-time loop unrolling

allo/backend/simulator.py
When building and lowering the simulator code, use `memref.store` for `allo.stream_get` and `memref.load` for `allo.stream_put` if FIFO elements are vectors, instead of the corresponding affine operations. This avoids the error that non-affine expression values can't be used as indices.
=> [Simulator][Dataflow] Fix non-scalar FIFO element access

allo/backend/aie.py, tests/dataflow/aie/test_matrix.py
This PR examines the DMA limits for memory tiles in NPU and creates an algorithm to dynamically distribute the transfer of input and output tensors across the allocated memory tiles. To better use the shards of DMAs in each memory tiles, the input and output dtensors are further split into parts according to the DMAs remaining.
[https://docs.amd.com/r/en-US/am020-versal-aie-ml/AIE-ML-Memory-Tile](url)
Currently the AIE backend can support GEMM design with 4x4 compute tiles.
```python
TyI, TyO = int16, int32
M, N, K = 128, 128, 128
P0, P1 = 4, 4
@df.region()
def top():
def gemm(A: TyI[M, K] @ LyA, B: TyI[K, N] @ LyB, C: TyO[M, N] @ LyC):
C[:, :] = allo.matmul(A, B)
```
```mlir
module {
aie.device(npu1_4col) {
func.func private …
```
=> [Backend][AIE] Support dynamic shim and memory tiles allocation based on input and output tensors and DMA limits

allo/customize.py, tests/test_schedule_compose.py
This PR fixes #352 by avoiding adding duplicated primitives to `primitive_sequences` when applying `s.compose`.
See #352.
=> [Primitive] Fix nested compose

allo/ir/builder.py, tests/test_builder.py
This PR fixes #355. The builder supposes Python AST `BoolOp` has only two arguments, which is right for multiple `and` and `or` statements used in an interleaved way. However, Python AST will wrap consecutive `and` statements to one `BoolOp` node, leading to the error. Basically we need to cascade the condition generation.
```python
def test_multiple_conditions():
def multiple_conditions(A: int32[3], b: int32, c: int32) -> int32:
r: int32 = 0
if A[0] > 0 and A[1] > 0 and A[2] > 0 and b > 0 and c > 0:
r = 1
return r
s = allo.customize(multiple_conditions)
np_A = np.array([1, 1, -1], dtype=np.int32)
assert mod(np_A, 1, 1) == multiple_conditions(np_A, 1, 1)
```
=> [Builder] Fix consecutive AND conditions

allo/backend/aie.py, allo/ir/builder.py, allo/passes.py, tests/dataflow/aie/test_matrix.py
This PR eliminates redundant local buffers by enabling buffer relaying in the builder. Specifically, if the left-hand side of an assignment is an already defined tensor, the result of the right-hand side computation is written directly into it, avoiding the creation of a new buffer and the subsequent `memref.copy`. The corresponding case will be the assignment for `A[:]` or `A[:, :]`. To ensure correctness, the target tensor is zero-initialized beforehand. This PR also adds support for external vectorized zero-initialization kernels in MLIR-AIE. Additionally, it fixes the recursive lookup strategy in the `analyze_read_write_pattern` function.
For this GEMM design,
```python
TyI, TyO = int16, int32
M, N, K = 128, 128, 128
P0, P1 = 4, 4
@df.region()
def top(): …
```
=> [Backend][AIE] Remove redundant local buffer through buffer relaying in builder and support zero external kernel

allo/autoscheduler/dfg.py, allo/autoscheduler/passes.py, tests/autoscheduler/test_autoscheduler.py, tests/autoscheduler/test_dfg.py
Implements the node parallel performance model described in the stream-hls paper (https://github.com/cornell-zhang/allo/discussions/297)
The previous MINLP formulation was adapted to use a symbolic expression for the first/last read/write times so that they could be expressed as a function of the loop tiling factor. The permutations are then fixed while the tiling factors are optimized for minimizing latency while respecting the DSP and tiling equality constraints. 
This kernel 
```python
def simple() -> float32[64, 64]:
A: float32[64, 64]
B: float32[64, 64]
for i in range(64):
for j in range(64):
A[i, j] = i + j
for j in range(64):
for i in range(64):
B[i, j] = A[i, j] + 1
return B
```
Produces the following MINLP, which, when solved, yields the (correct) solution of fully tiling each …
=> [Autoscheduler] Node parallel performance model

tests/dataflow/aie/test_summa.py
This PR adds a SUMMA matrix multiplication example. In the 2x2 example, two full outer products are calculated and summed. In the 4x4 example (which also works for 2x2 tiles), columns of A are multiplied with sharded pieces of B and each row of compute tiles sums columns of the output, essentially dividing up 4 outer products into 16 cores. This code is provided.
```
def _test_summa():
Ty = int32
M, K, N = 32, 32, 32
P0, P1 = 4, 4
La = Layout("RS0")
Lb = Layout("S0S1")
Lc = Layout("RS1")
@df.region()
def top():
column_fifo = df.array(
df.pipe(dtype=Ty, shape=(M, N // P0), depth=1), shape=(P0, P1 - 1)
)
def summa(B: Ty[K, N] @ Lb, A: Ty[M, K] @ La, C: Ty[M, N] @ Lc):
i, j = df.get_pid()
P_tile: Ty[M, N // P0] = allo.matmul(A, B)
with allo.meta_if(j == 0): …
```
=> [Dataflow][AIE] Add SUMMA example

allo/backend/experimental/README.md, allo/backend/experimental/__init__.py, allo/backend/experimental/mlir_codegen.py, allo/backend/experimental/utils.py, allo/dataflow.py
This PR introduces a new feature to the `AIE_MLIRModule` class. The goal is to enable users to easily profile the performance of their module executions by measuring runtime over multiple iterations. 
Previously, there was no built-in way to evaluate the performance of modules.
Previously, the `top_func_name` when building aie module was hardcoded as `top`.
- Extend host code construction to include profiling option.
- Added `profile`, `warmup`, and `num_iters` parameters to the `build` method.
- When `profile=True`, the module performs:
- A configurable number of warm-up runs (default: 20) to stabilize performance.
- A configurable number of timed runs (default: 100) to gather average execution time.
- Print average execution time to the console.
- Fix bug to enable different …
=> [Backend][AIE][Profiling] Enable profiling AIE module and fix bugs

.github/workflows/config.yml, .github/workflows/sphinx_build.yml, allo/backend/__init__.py, allo/backend/experimental/README.md, allo/backend/experimental/__init__.py, allo/backend/experimental/external_kernel.py, allo/dataflow.py, requirements.txt, requirements_extra.txt
Make the aie package optional and revert to the original installation method without prebuilt wheels to improve compatibility, 
In previous PR #368 , we configured the MLIR-AIE environment via prebuilt wheels by updating `requirements.txt`:
```
mlir_aie @ https://github.com/Xilinx/mlir-aie/releases/download/v1.0/mlir_aie-0.0.1.2025042204+24208c0-cp312-cp312-manylinux_2_35_x86_64.whl
llvm_aie @ https://github.com/Xilinx/llvm-aie/releases/download/nightly/llvm_aie-19.0.0.2025041501+b2a279c1-py3-none-manylinux_2_27_x86_64.manylinux_2_28_x86_64.whl
```
However, the mlir_aie wheel require `manylinux_2_35`, and some systems (e.g., those with glibc 2.34, as confirmed by `ldd --version`) do not meet this requirement. This results in an installation failure like:
```
ERROR: …
```
=> [AIE][Environment] Make aie package optional due to compatibility issues

setup.py
The CMake build for the MLIR components for Allo depends on pybind11. pybind11 is already a run-time requirement (i.e., listed in `requirements.txt`), but it also needs to be required at build time to make isolated builds possible.
In a [PEP 517](https://peps.python.org/pep-0517/)-style isolated build, no system-installed Python modules are available during the execution of `setup.py` and therefore of CMake. To make this work, we need to explicitly declare all the build-time dependencies—here, just pybind11.
Add a pybind11 requirement to `setup_requires` in `setup.py`.
Try using [uv][] to build and install Allo into a virtualenv:
```
LLVM_BUILD_DIR=`pwd`/externals/llvm-project/build uv pip install -e .
```
Without this declared dependency, we'll get an error like this:
```
CMake Error at …
```
=> [build] Declare setup-time dependency on pybind11

allo/frontend/pytorch.py, allo/ir/symbol_resolver.py, allo/library/nn.py, examples/torch/mlp.py, tests/test_nn.py
This PR fixes #387 by providing an interface for specifying the data types for each operation in PyTorch. Currently users can pass in a dictionary (mapping from PyTorch module name to input/output data types) to `op_dtypes` in the `allo.frontend.from_pytorch` function. All the Allo [data types](https://cornell-zhang.github.io/allo/gallery/dive_01_data_types.html) are supported, but users need to guarantee the correct data types between operations. NO automatic type conversion is added in this PR.
```python
llvm_mod = allo.frontend.from_pytorch(
model,
example_inputs=example_inputs,
verbose=True,
weights_as_args=True,
op_dtypes={
"inputs": float32,
"linear1": [float32, Fixed(64, 30), float32],  # X, W, O for first linear
"linear2": [float32, Fixed(64, 30), float32],  # X, W, O for second …
```
=> [Frontend] Support specifying data types for PyTorch models

allo/frontend/library.py, allo/frontend/pytorch.py, allo/library/__init__.py, allo/library/nn.py, examples/torch/particle_transformer.py, tests/test_nn.py
This PR fixes cornell-zhang/allo#386 and enhances the PyTorch frontend in the allo library to support additional operations commonly used in Transformer models.
The current PyTorch frontend lacks support for several commonly used Transformer components, leading to conversion failures when compiling models.
Unsupported features include:
- `build_get_attr` handling for cls_token to avoid attribute access errors
- `repeat` for CLS token expansion
- `log_softmax` operator
- `BatchNorm1d` supporting both 2D (B, C) and 3D (B, C, L) inputs
- `relu3d` (previously only relu2d and relu4d existed)
- `concat` for sequence concatenation, used to prepend CLS token
- Slice operation to extract CLS token (Allo currently does not support slicing)
- Fix bug: add build_get_attr support for cls_token …
=> [Frontend][PyTorch][Bugfix][Feature] Add support for common Pytorch operations (repeat, batchnorm1d, log_softmax)

allo/customize.py, allo/library/systolic.py, playground/int8_gemm.py
This PR fixes a legacy SA issue where the original SA based on Allo's schedule cannot achieve the expected performance.
This is mainly due to the incorrect pipelined loops for data loading/storing.
The old performance result (8x8 GEMM using 2x2 SA):
```
+ Latency: 
* Summary: 
+---------+---------+----------+----------+-----+-----+----------+
|  Latency (cycles) |  Latency (absolute) |  Interval | Pipeline |
|   min   |   max   |    min   |    max   | min | max |   Type   |
+---------+---------+----------+----------+-----+-----+----------+
|      725|      727|  2.416 us|  2.423 us|  454|  454|  dataflow|
+---------+---------+----------+----------+-----+-----+----------+
+ Detail: 
* Instance: 
+-----------------+--------------+---------+---------+----------+----------+-----+-----+-------- …
```
=> [Library] Fix legacy systolic array performance issue

allo/backend/simulator.py, examples/feather/gemm.py
The original simulator does not count for integer bitwidth casting when generating the omp code, causing it to fail MLIR formatting check. This PR fixes this issue by adding explicit casting to the simulator code.
Failed example:
```mlir
"memref.store"(%273, %277, %283) : (i9, memref<2xi8>, index) -> ()
```
See the FEATHER int8 example.
=> [Simulator] Fix low-bitwidth simulation

mlir/lib/Translation/EmitVivadoHLS.cpp
This PR fixes a naming conflict when using bit operations with `allo.meta_for` (explicit unrolling) for the HLS backend
Old code:
```cpp
ap_int<128> v65_tmp = v65;
int8_t v66 = v66_tmp(7, 0);	// L108
v48.write(v66);	// L109
ap_int<128> v65_tmp = v65;  // naming conflict
int8_t v67 = v65_tmp(15, 8);	// L110
v49.write(v67);	// L111
```
New generated code:
```cpp
int8_t v66;
ap_int<128> v66_tmp = v65;
v66 = v66_tmp(7, 0);	// L108
v48.write(v66);	// L109
int8_t v67;
ap_int<128> v67_tmp = v65;
v67 = v67_tmp(15, 8);	// L110
v49.write(v67);	// L111
```
=> [Backend][Bugfix] Fix naming conflicts in bit operations when targeting HLS

tests/dataflow/test_packed_systolic.py
This PR tries to add a test case for packed systolic using the Dataflow module
I have added a test case called  `tests/dataflow/test_packed_systolic.py`; but I'm still trying to figure out the indexing problems on [this line](https://github.com/cornell-zhang/allo/blob/9abe4253ac2b7f3046e27bc15604af2544a264b5/tests/dataflow/test_packed_systolic.py#L61), which raises:
```c
File "allo/allo/ir/builder.py", line 1232, in build_Subscript
return ASTTransformer.build_bit_operation(ctx, node, val=val, idx=idx)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "allo/allo/ir/builder.py", line 1152, in build_bit_operation
value = build_stmt(ctx, node.value)
^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "allo/allo/ir/builder.py", line 73, in __call__
res = method(ctx, node, **kwargs) …
```
=> [Dataflow][Example] Packed systolic array for GEMM
